In [1]:
# implementing logistic regression

In [20]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# logistic regression by sklearn
from sklearn.linear_model import LogisticRegression

In [28]:
# importing dataset

dataset = pd.read_excel('Machine Learning Algos.xlsx',sheet_name='Logistic Regression').head(12)
dataset

Height (cm)  Label       sig          f(X)     error            WF  \
0         120.0    0.0  0.000006 -5.421616e-07  0.000006  4.369884e-09   
1         124.0    0.0  0.000014 -1.240214e-06  0.000014  2.362882e-08   
2         125.0    0.0  0.000017 -1.525240e-06  0.000017  3.602563e-08   
3         128.0    0.0  0.000032 -2.837008e-06  0.000032  1.276288e-07   
4         130.0    0.0  0.000048 -4.290814e-06  0.000048  2.965050e-07   
5         129.0    0.0  0.000039 -3.488996e-06  0.000039  1.945380e-07   
6         180.0    1.0  0.597300 -9.081088e-01 -0.402700 -1.743524e+01   
7         185.0    1.0  0.806680 -7.776001e-01 -0.193320 -5.577327e+00   
8         190.0    1.0  0.921502 -7.198051e-01 -0.078498 -1.078862e+00   
9         195.0    1.0  0.970610 -6.972565e-01 -0.029390 -1.634803e-01   
10        200.0    1.0  0.989352 -6.889508e-01 -0.010648 -2.243628e-02   
11        205.0    1.0  0.996189 -6.859598e-01 -0.003811 -2.966337e-03   

    y_pred         b  -36.8424613773466  Unnamed: 9  
0      0.0         w           0.206870         NaN  
1      0.0  examples          12.000000         NaN  
2      0.0        lr           0.020000         NaN  
3      0.0        nb         -36.828097  -36.842461  
4      0.0        nw           0.247338    0.206870  
5      0.0       NaN                NaN         NaN  
6      1.0       NaN                NaN         NaN  
7      1.0       NaN                NaN         NaN  
8      1.0       NaN                NaN         NaN  
9      1.0       NaN                NaN         NaN  
10     1.0       NaN                NaN         NaN  
11     1.0       NaN                NaN         NaN

In [29]:
# selecting features
features = dataset['Height (cm)']
# selecting labels
labels = dataset['Label']

In [30]:
# logistic regression by sklearn
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(features.values.reshape(-1,1), labels)
logreg.coef_, logreg.intercept_

(array([[0.24473587]]), array([-38.31130303]))

In [31]:
# sklearn cost function
from sklearn.metrics import log_loss
log_loss(labels, logreg.predict_proba(features.values.reshape(-1,1)))

0.0007565415791482275

In [32]:
# implementing logistic regression from scratch
def sigmoid(x):
    return 1/(1+np.exp(-x))



In [33]:
def cost_function(features, labels, weights):
    m = len(labels)
    predictions = sigmoid(np.dot(features, weights))
    cost = (1/m) * np.sum(-labels*np.log(predictions) - (1-labels)*np.log(1-predictions))
    return cost

In [34]:
def update_weights(features, labels, weights, lr):
    m = len(labels)
    predictions = sigmoid(np.dot(features, weights))
    gradient = np.dot(features.T, predictions-labels)
    weights -= lr * gradient
    return weights

In [35]:
def train(features, labels, weights, lr, iters):
    cost_history = []
    for i in range(iters):
        weights = update_weights(features, labels, weights, lr)
        cost = cost_function(features, labels, weights)
        cost_history.append(cost)
    return weights, cost_history

In [36]:
# training the model
weights = np.zeros(2)
features = np.c_[np.ones(len(features)), features]
weights, cost_history = train(features, labels, weights, 0.01, 10000)

<ipython-input-33-7f289d54c47c>:4: RuntimeWarning: divide by zero encountered in log
  cost = (1/m) * np.sum(-labels*np.log(predictions) - (1-labels)*np.log(1-predictions))
<ipython-input-32-8bbfccdbd8ac>:3: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [37]:
weights

array([-41.27559218,   0.26498447])

In [38]:
cost_history[-1]

0.0004457758460319275

In [39]:
# predicting the labels
def predict(features, weights):
    z = np.dot(features, weights)
    return sigmoid(z)

predictions = predict(features, weights)
predictions

array([7.65526188e-05, 2.20913635e-04, 2.87921904e-04, 6.37333532e-04,
       1.08227084e-03, 8.30546762e-04, 9.98376608e-01, 9.99567949e-01,
       9.99885114e-01, 9.99969458e-01, 9.99991881e-01, 9.99997842e-01])

In [40]:
# applying threshold
predictions = np.where(predictions > 0.5, 1, 0)
predictions

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [41]:
# creating a dataframe of all the predictions
df = pd.DataFrame({'features': features[:,1], 'labels': labels, 'sigmoid': predict(features, weights), 'error': labels-predictions, 'y_pred': predictions})
df

features  labels   sigmoid  error  y_pred
0      120.0     0.0  0.000077    0.0       0
1      124.0     0.0  0.000221    0.0       0
2      125.0     0.0  0.000288    0.0       0
3      128.0     0.0  0.000637    0.0       0
4      130.0     0.0  0.001082    0.0       0
5      129.0     0.0  0.000831    0.0       0
6      180.0     1.0  0.998377    0.0       1
7      185.0     1.0  0.999568    0.0       1
8      190.0     1.0  0.999885    0.0       1
9      195.0     1.0  0.999969    0.0       1
10     200.0     1.0  0.999992    0.0       1
11     205.0     1.0  0.999998    0.0       1

In [42]:
df = pd.DataFrame({'features': features[:,1]})

In [43]:
df

features
0      120.0
1      124.0
2      125.0
3      128.0
4      130.0
5      129.0
6      180.0
7      185.0
8      190.0
9      195.0
10     200.0
11     205.0

In [44]:
df = pd.DataFrame({ 'labels': labels,})

In [45]:
df

labels
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      1.0
7      1.0
8      1.0
9      1.0
10     1.0
11     1.0

In [46]:
df = pd.DataFrame({ 'sigmoid': predict(features, weights)})

In [47]:
df

sigmoid
0   0.000077
1   0.000221
2   0.000288
3   0.000637
4   0.001082
5   0.000831
6   0.998377
7   0.999568
8   0.999885
9   0.999969
10  0.999992
11  0.999998